### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by Ray94520** [Klettner/MMM-StopwatchTimer#4]
So I just installed your module stopwatch timer
it works very well. I like it quite a bit
so I have 2 questions
1st 1 is, is it possible to add sound when the timer has ended
in the 2nd 1 is the large black background. Is it possible to not show that and just show the timer

**Comment by Klettner** [comment]
Hi, 
thanks for your feedback.
About 1:
I just found a module that makes it possible to play sound on the Mirror https://github.com/jc21/MMM-Sounds and I'm thinking about integrating it.
About 2:
Unfortunately this is currently not possible.

**Comment by Ray94520** [comment]
Well thank you for answering my reply
I really do like your module so I hope you can solve the lack of sound that would be awesome
I'm okay with the black background. I can live with that
please let me know when you have added the sound

**Comment by Klettner** [comment]
The sound is now added, but I was not able to test it because my mirror is not connected to any speakers. 
Please let me know if everything works properly!

Setup:
* Install the sound module:  https://github.com/jc21/MMM-Sounds 
  * Make sure that the sound output of this module works

Update MMM-StopwatchTimer:
* Access the folder of this module in your terminal:  
``cd ~/MagicMirror/modules/MMM-StopwatchTimer``
* Get the changes:  
``git pull``
* Install the changes:  
``npm i``

(Optional) change the sound in config.js:
```
modules: [
  {
    module: 'MMM-StopwatchTimer',
    config: {
      animation: true,
      sound: true,
      soundFile: 'buzz.wav'
    },
  },
];
```
* You can change soundFile to any file that was added to the [MMM-Sounds](https://github.com/jc21/MMM-Sounds) module

**Comment by Ray94520** [comment]
Thank you very much for the update on the sound. I will certainly check it
out

Just to let you know though I currently use the notification and alert in
my magic mirror changing colors and things like that

I found the problem with your module. It causes a conflict between my
desires in magic mirror and your module your module calls up
notificationFX.css. Hence the conflict

I was able to fix it by renaming popup.css to MMM-StopwatchTimer.css
and then changing it in

getStyles: function() {
return ["MMM-StopwatchTimer.css", "font-awesome.css"];
},

And now it works perfectly. No more conflicts between alert and
MMM-StopwatchTimer.js a friend of mine had the same problem

If you don't use alert or notification. You won't see the conflict

By making these changes. I hope you don't mind

I'm letting you know about this because
others might be running into the same problem

It's a great module. I really do like it. Thanks for all your hard work

**Comment by Ray94520** [comment]
P.S

I'm assuming it will be like this

notificationExec: {
        notification: "START_TIMER",
        payload: 1 *60,
soundFile:
sound: "buzz.wav",
      },

Is this correct

**Comment by Klettner** [comment]
Thanks for letting me know, I will change it according to your explanations 👍 

> Thank you very much for the update on the sound. I will certainly check it out Just to let you know though I currently use the notification and alert in my magic mirror changing colors and things like that I found the problem with your module. It causes a conflict between my desires in magic mirror and your module your module calls up notificationFX.css. Hence the conflict I was able to fix it by renaming popup.css to MMM-StopwatchTimer.css and then changing it in getStyles: function() { return ["MMM-StopwatchTimer.css", "font-awesome.css"]; }, And now it works perfectly. No more conflicts between alert and MMM-StopwatchTimer.js a friend of mine had the same problem If you don't use alert or notification. You won't see the conflict By making these changes. I hope you don't mind I'm letting you know about this because others might be running into the same problem It's a great module. I really do like it. Thanks for all your hard work
> […](#)

**Comment by Klettner** [comment]
> P.S I'm assuming it will be like this notificationExec: { notification: "START_TIMER", payload: 1 *60, soundFile: sound: "buzz.wav", }, Is this correct
> […](#)

The notifications for this module are unchanged. Thus, there is no need to specify "soundFile" or "sound" in the notification.
Only in the config/config.js file two new options are added:
* `` sound: true ``  can be set to true or false. It is used to determine if a sound should be played when the timer is done
* ``soundFile: 'buzz.wav'`` is used to specify the soundFile that should be used.

I hope that helps

**Comment by Ray94520** [comment]
👍

**Comment by bugsounet** [comment]
@Klettner: I added native sound support for your module (with no break change actually)

If you need help for other, just tell me ;)
For displaying, I think it's not a good idea to use `alert` module
After it's your choice ;)

@bugsounet

**Comment by Klettner** [comment]
@bugsounet: I merged your changes, thanks for your help 

I do appreciate it :)

**Comment by Ray94520** [comment]
I was happy to help

**Comment by bugsounet** [comment]
@Klettner : if you want help for design new timeout displaying without `alert` module (I really hate, sorry !)
Just mention me, I can code something else (simple and quickly, with or without animation) with a popup

**Comment by Ray94520** [comment]
So after reinstalling your module. It now works 100% better
you still have an issue though with. You can't change the defaults in custom.css
the only way is to modify mmm.StopwatchTimer.css changes in my opinion should be gone in custom.css

Other than that it works perfectly. I even like the new popup
I so bugsounet had his hand in their he's a good guy

Nice work. Good job

**Comment by bugsounet** [comment]
Thanks Ray
I can make it directly in config ;)
 ... but I don't want to do all job !
I just send the way to @Klettner (I think)
After If it need some Help, I can contact me and i will offer my help with kindness

It's @Klettner module and not mine ;)

In all case, happy use with this new part of code guys!
@bugsounet
